### ISSUE TITLE
Make fade-in duration a customisable parameter

### ISSUE THREAD

**Issue by dschreij** [MatteoGabriele/vue-progressive-image#11]
Thanks for creating this great module. I have one request.
Before the placeholder is loaded, the image is faded in from grey (as it seems), but this goes a little bit too slow for my taste. Would it be possible to make this fade-in speed customisable per parameter, as you currently also already allow for blur amount and delay?

**Comment by MatteoGabriele** [comment]
I have actually tried, but then I just realized that as it is now, is not possible to customize the transition between the placeholder and the main image because the transition-delay property is assigned to another class and I have no access on that class during the animation.

If you have any idea on how to implement this feature, would be nice

**Comment by dschreij** [comment]
Thanks! I will think about it. I haven't got any in-depth knowledge of your module yet, but if I have the time I will have a look. And if it is too much trouble to implement this, then it is fine as it is.

**Comment by MatteoGabriele** [comment]
I'll leave the ticket open, maybe someone wants to pick it up: you never know 😄 
Or maybe I will think about something else to handle animations, but css is the most cheap animation I can think of.

**Comment by merijnvdk** [comment]
Can it not be done by adding these features to separate css classes and conditionally assigning the css classes? (I did not dive into this yet)
Same thing maybe for the 'zoom' effect transition from placholder to main image. personally i would like to disable it. maybe I can with css, have not tried yet.

**Comment by MatteoGabriele** [comment]
It's not that easy. How to do you change all the classes? how do you assign classnames for the animations. 
You should have a deep look at the structure of the plugin, is not very difficult but it has its own complexity: took me a while to figure out the right balance to be not too "opinionated" and do what he was suppose to do.
If you add too much css that it's impossible to style, if you don't add enough then it doesn't work.

but please @merijnvdk fork it and see if you can figure out a better way.
I believe that going totally js also with style might work better: I was thinking about something close to css-in-js or styled component, so that it's possible to pass properties.

**Comment by merijnvdk** [comment]
I've looked at this and as these tweaks can be done by css styling. So I think the best solution for this issue is to update the readme with a section about styling this plugin.

Could add something like this:

````
/* disable 'zoom' effect on image placeholders (default: translateZ(0px) scale(1.1)) */
.your-app-class .progressive-image-placeholder {
	transform :none;
}
/* make translation from placeholder to original image faster (default 1.2s) */
.your-app-class .progressive-image-main {
	transition-duration: 0.5s;
}
````

**Comment by MatteoGabriele** [comment]
But I guess this it's just common sense: if you need to tweak something just override the styling.
If you think that is not obvious can be added for sure.
Still want to add examples and stuff like this, but I always forget that 😆

**Comment by merijnvdk** [comment]
Its obvious if you know the plugin in and out, but it requires some diving-in to find out how and where things are done. So some simple examples for the most likely use-cases would improve the user-friendlyness of this plugin. But I agree its just a *nice to have*.

**Comment by MatteoGabriele** [comment]
True that! I definitely have to spend some time to add some examples

**Comment by MatteoGabriele** [comment]
Well since @merijnvdk found a way to change those properties, I close this ticket.
There's already an issue for the "example" ( see #14 ) :)
