### ISSUE TITLE
How do I style these images?

### ISSUE THREAD

**Issue by rchrdnsh** [MatteoGabriele/vue-progressive-image#16]
I dropped the <progressive-img> plugin into my app, then replaced an <img> tag with it, and all the images in my v-for loop got super small...so I don't know what to do to make it work right, css wise. My standard CSS for images is:

```
img {
  width: 100%;
  height: auto;
}
```
...for all images to be responsive. So that apparently does not work for this plugin, so what is the appropriate styling for <progressive-img> to work properly while still retaining responsive images?

**Comment by MatteoGabriele** [comment]
Images should already be responsive by default with this plug-in. Could u make a small reproduction so that I can have a look? 
It's hard to say because I don't know the css applied in your application.

**Comment by MatteoGabriele** [comment]
I will close this one for inactivity

**Comment by desprit** [comment]
Hi @MatteoGabriele 

Issue with styles is real and it happens when styles are scoped. I was using `vue-loader` version ~11.x.x and this syntax:
```
<style lang="stylus" scoped> 
    .container
        .progressive-image-wrapper
            img
                width: 300px
</style>
```
doesn't work. If I remove `scoped` attribute, it works fine. I'm not sure why and how but it was fixed in `vue-loader` v.12.2.x+:
https://github.com/vuejs/vue-loader/releases/tag/v12.2.0

```
<style lang="stylus" scoped> 
    .container
        >>> .progressive-image-wrapper
            img
                width: 300px
</style>
```

Leaving it here just in case someone else faces same issue.

**Comment by MatteoGabriele** [comment]
Yeah true, now I remember that! 
Thanks man :)
