### ISSUE TITLE
Variable usage

### ISSUE THREAD

**Issue by visualcookie** [MatteoGabriele/vue-progressive-image#5]
I'm having a data variables of `movieBackdropSrc`, which gets filled by an API. Now I want to be able to have the image loading, but it won't work.

Code I'm using: `<progressive-background src="movieBackdropSrc" />`.
I also tried `<progressive-background :src="movieBackdropSrc" />`.

**Comment by MatteoGabriele** [comment]
Can you be more specific, please? :)
Maybe a some code.

if you want to pass a variable instead of string then it's mandatory to pass it with semi colons or it will try to load the string `movieBackdropSrc` as an image.

If you need to load images from an api end point probably you want to use an `v-if` in the progressive-image instance. 

Progressive image handles image loading process, doesn't wait until your variable is evaluated from `undefined` to `image.jpg`: it's something that you need to handle.

if you try to do the same with a normal images, you will probably have the same issue.

**Comment by visualcookie** [comment]
Can't really show much code here, since it's still a private project. What did the trick, as you already said, was using `v-if`.

`<progressive-background v-if="backdropVisible" :src="movieBackdropSrc" />`

Thanks so far, for the help. :)

**Comment by MatteoGabriele** [comment]
@visualcookie you're welcome :)
