### ISSUE TITLE
Blur on Progressive background also

### ISSUE THREAD

**Issue by GeorgeChackungal** [MatteoGabriele/vue-progressive-image#55]
First and foremost nice job with the library. I was wondering if its possible to add the blur to the original image as well or if you could suggest a way to do it dynamically.

Thanks!

**Comment by MatteoGabriele** [comment]
Hey @GeorgeChackungal thanks for the feedback :)
it's currently not possible, but if if you add the `placeholder` attribute and you pass the same source that you add in the `src` attribute, you should be able to achieve a face effect.

```html
<progressive-img
  src="main_image_path"
  placeholder="main_image_path">
</progressive-img>
```

The fade will be quite fast because the file has been already downloaded by the placeholder so transition will be much faster.
If you want to force a slower transition you can adjust the delay value in the global settings of the plugin.

Best option will be to really have a 3kb version of the same image to load as placeholder and let the plugin handle the main big file.

let me know if works for you.

Thanks
