### ISSUE TITLE
Add ability to upscale images

### ISSUE THREAD

**Issue by Cobrand** [MatteoGabriele/vue-progressive-image#59]
I may obviously be mistaken and be using this component incorrectly, but it looks like any `progressive-img` is limited in width to the original image's width. (from this line: https://github.com/MatteoGabriele/vue-progressive-image/blob/master/src/mixin/image.js#L113)

During my tests, if an image had an original width of 250px, I couldn't make it 270px, 300 or 500px. I haven't seen an issue about this, (which seems weird), but I haven't seen any option to prevent this either.

Is this a mistake on my end and possible after all? If not, is there any plans to add this as a possibility in the future?

**Comment by MatteoGabriele** [comment]
yeah I've seen this once when I was testing some features, but didn't have time to investigate.

thanks

**Comment by MatteoGabriele** [comment]
@Cobrand can you specify the version you are using, because I believe that this has been fixed already.

thanks

**Comment by MatteoGabriele** [comment]
ah wait but I'm now reading it better: you cannot over stretch an image because it shouldn't happen in the first place.
if you want to fit an image in a div, then you might want to use the `progressive-background` component, instead of `progressive-img`.

so instead of `progressive-img`, just type `progressive-background` and you should be fine.
