### ISSUE TITLE
Duplicate image after filtering tags/category/searchs

### ISSUE THREAD

**Issue by AnonimBella** [MatteoGabriele/vue-progressive-image#61]
Here's a preview of bugs:
![image](https://user-images.githubusercontent.com/13130920/49714594-05e97700-fc80-11e8-923d-d82d278f736d.png)

That's preview after I filter tags/category/searches via ajax. I use Vue, and filter in same pages using ajax. The content (title & caption) displayed is correct (no duplicate), but only the real image is duplicate.
Even when I check through inspectelement, the progressive img placeholder source is correct.

Is it because of cache?

And when I force to refresh with the same url, there is no problem. Here's the previews:
![image](https://user-images.githubusercontent.com/13130920/49715021-b1df9200-fc81-11e8-9048-dddd8e3f4b90.png)

I'm really confused. I don't want to change the library,

**Comment by MatteoGabriele** [comment]
Could you recreate this on a repository so I can have a look? Thanks :)

**Comment by AnonimBella** [comment]
Sorry this projects already published in production live, so I cannot give an access. The feature in landing page. You can test by click the tags which background is green, or click the category, or search something on the page.

**Comment by MatteoGabriele** [comment]
hey @AnonimBella sorry but I didn't mean to have access to a private project, is not what I need. You need to create a brand new project, with a very basic configuration and reproduce the same behavior that you are having so that I'm sure that is not your code doing something strange and that I can easily have your same problem and I can probably fix it easier.

A reproduction of a bug is very important for me, otherwise it's very hard to understand.

Cheers

**Comment by AnonimBella** [comment]
Oh ok, I will create repo. I will inform you again if i already create it.

**Comment by AnonimBella** [comment]
Hi! @MatteoGabriele I have solved this issue. There is something wrong with my code, it's function of route query. Sorry for waste your time, thanks :)
